WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppAspNetMvcDatabaseQuery.Models
{
    public class Client
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Имя клиента
        /// </summary>
        [Required]
        [Display(Name = "Имя клиента", Order = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Фамилия клиента
        /// </summary>
        [Required]
        [Display(Name = "Фамилия клиента", Order = 10)]
        public string Surname { get; set; }

        /// <summary>
        /// Возраст клиента
        /// </summary>
        [Required]
        [Display(Name = "Возраст клиента", Order = 20)]
        public int Age { get; set; }

        /// <summary>
        /// Дата рождения
        /// </summary>

        [Display(Name = "Дата рождения", Order = 30)]
        public DateTime? Birthday { get; set; }
    }
}

WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Controllers/ClientsController.cs
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Configuration;
using System.Web.Mvc;
using WebAppAspNetMvcDatabaseQuery.Models;

namespace WebAppAspNetMvcDatabaseQuery.Controllers
{
    public class ClientsController : Controller
    {
        public readonly string _connectionString = WebConfigurationManager.AppSettings["ConnectionString"];

        [HttpGet]
        public ActionResult Index()
        {
            var clients = SelectClients();
            return View(clients);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var client = new Client();

            return View(client);
        }

        [HttpPost]
        public ActionResult Create(Client model)
        {
            if (!ModelState.IsValid)
                return View(model);

            

            InsertClient(model);

            return RedirectPermanent("/Clients/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var client = SelectClients().FirstOrDefault(x => x.Id == id);
            if (client == null)
                return RedirectPermanent("/Clients/Index");

            DeleteClient(client);

            return RedirectPermanent("/Clients/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var client = SelectClients().FirstOrDefault(x => x.Id == id);
            if (client == null)
                return RedirectPermanent("/Clients/Index");

            return View(client);
        }

        [HttpPost]
        public ActionResult Edit(Client model)
        {
            var client = SelectClients().FirstOrDefault(x => x.Id == model.Id);
            if (client == null)
                ModelState.AddModelError("Id", "Книга не найдена");

            if (!ModelState.IsValid)
                return View(model);

            MappingClient(model, client);

            UpdateClient(client);

            return RedirectPermanent("/Clients/Index");
        }

        private void MappingClient(Client sourse, Client destination)
        {
            destination.Name = sourse.Name;
            destination.Surname = sourse.Surname;
            destination.Age = sourse.Age;
            destination.Birthday = sourse.Birthday;
        }



        public void InsertClient(Client client)
        {
            IDbConnection connection = new SqlConnection(_connectionString);

            string cmdStr = $@"INSERT INTO [{connection.Database}].[dbo].[Clients] ([Name], [Surname], [Age], [Birthday])  VALUES (@Name,@Surname, @Age, @Birthday)";
            IDbCommand cmd = new SqlCommand(cmdStr);
            cmd.Connection = connection;
            connection.Open();

            cmd.Parameters.Add(new SqlParameter("@Name", client.Name));
            cmd.Parameters.Add(new SqlParameter("@Surname", client.Surname));
            cmd.Parameters.Add(new SqlParameter("@Age", client.Age));
            cmd.Parameters.Add(new SqlParameter("@Birthday", client.Birthday));
            

            cmd.ExecuteNonQuery();
            connection.Close();
        }
        public void UpdateClient(Client client)
        {
            IDbConnection connection = new SqlConnection(_connectionString);

            string cmdStr = $@"UPDATE [{connection.Database}].[dbo].[Clients] SET [Name] = @Name, [Surname] = @Surname , [Age] = @Age, [Birthday] = @Birthday WHERE Id = {client.Id}";
            IDbCommand cmd = new SqlCommand(cmdStr);
            cmd.Connection = connection;
            connection.Open();

            cmd.Parameters.Add(new SqlParameter("@Name", client.Name));
            cmd.Parameters.Add(new SqlParameter("@Surname", client.Surname));
            cmd.Parameters.Add(new SqlParameter("@Age", client.Age));
            cmd.Parameters.Add(new SqlParameter("@Birthday", client.Birthday));

            cmd.ExecuteNonQuery();
            connection.Close();
        }
        public void DeleteClient(Client client)
        {
            IDbConnection connection = new SqlConnection(_connectionString);

            string cmdStr = $@"DELETE [{connection.Database}].[dbo].[Clients] WHERE Id = {client.Id}";
            IDbCommand cmd = new SqlCommand(cmdStr);
            cmd.Connection = connection;
            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();
        }
        public List<Client> SelectClients()
        {
            IDbConnection connection = new SqlConnection(_connectionString);

            string cmdStr = $"SELECT * FROM [{connection.Database}].[dbo].[Clients]";
            IDbCommand cmd = new SqlCommand(cmdStr);
            cmd.Connection = connection;
            connection.Open();

            IDataReader read = cmd.ExecuteReader();
            var clients = new List<Client>();
            while (read.Read())
            {
                var parser = read.GetRowParser<Client>(typeof(Client));
                var client = parser(read);
                clients.Add(client);
            }

            connection.Close();
            return clients;
        }
    }
}

WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Views/Clients/Create.cshtml
@using WebAppAspNetMvcDatabaseQuery.Models
@model Client

<h3>Клиент</h3>

@using (Html.BeginForm("Create", "Clients", FormMethod.Post))
{
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "Clients")
}

WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Views/Clients/Edit.cshtml
@using WebAppAspNetMvcDatabaseQuery.Models
@model Client

<h3>Клиент</h3>

@using (Html.BeginForm("Edit", "Clients", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "Clients")
}

WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Views/Clients/Index.cshtml
@using WebAppAspNetMvcDatabaseQuery.Models
@model List<Client>

<h3>Клиенты</h3>

@Html.ActionLink("Добавить запись", "Create", "Clients")

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                Имя клиента
            </th>
            <th>
                Фамилия клиента
            </th>
            <th>
                Возраст клиента
            </th>
            <th>
                Дата рождения
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var client in Model)
        {
            <tr>
                <td>
                    @client.Name
                </td>
                <td>
                    @client.Surname
                </td>
                <td>
                    @client.Age
                </td>
                <td>
                    @client.Birthday.Value.ToString("dd-MM-yyyy")
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", "Clients", new { id = client.Id }, new { })
                    @Html.ActionLink("Изменить", "Edit", "Clients", new { id = client.Id }, new { })
                </td>
            </tr>
        }
    </tbody>
</table>

WebAppAspNetMvcDatabaseQuery/WebAppAspNetMvcDatabaseQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Госуслуги</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Клиенты", "Index", "Clients")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>